[package]
name = "ghost"
version = "0.0.1"
authors = ["skanehira"]
edition = "2024"

[dependencies]
clap = { version = "4.5.31", features = ["derive"] }
uuid = { version = "1.11", features = ["v4"] }
thiserror = "2.0"
dirs = "5.0"

[target.'cfg(unix)'.dependencies]
nix = { version = "0.29", features = ["signal", "process"] }

[dev-dependencies]
tempfile = "3.14"
