name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  # for goreleaser
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: (setup) sccache
        uses: mozilla-actions/sccache-action@v0.0.9
      
      - name: (setup) environment variables for sccache
        shell: bash
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> "$GITHUB_ENV"
          echo "RUSTC_WRAPPER=sccache" >> "$GITHUB_ENV"

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-shared-key: setup-rust-${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock') }}
          target: "x86_64-unknown-linux-gnu, x86_64-apple-darwin, aarch64-unknown-linux-gnu, aarch64-apple-darwin"
          rustflags: "" # override default rustflags

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: true

      - name: Install cargo-cross
        run: |
          cargo install cross --locked

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test cargo-cross with a simple target
        run: |
          cross --version
          echo "Testing cross compilation for x86_64-unknown-linux-gnu"
          cross build --target x86_64-unknown-linux-gnu --release

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean --verbose
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
